DROP TABLE IF EXISTS horseracing_user CASCADE;
DROP TABLE IF EXISTS horseracing_admin CASCADE;
DROP TABLE IF EXISTS horse CASCADE;
DROP TABLE IF EXISTS race CASCADE;
DROP TABLE IF EXISTS bet CASCADE;
DROP TABLE IF EXISTS result CASCADE;

CREATE TABLE horseracing_user (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  amount REAL NOT NULL DEFAULT 100.0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE horseracing_admin (
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE race (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  number INTEGER UNIQUE NOT NULL,
  venue TEXT NOT NULL,
  distance TEXT,
  type TEXT,
  field TEXT,
  open INTEGER NOT NULL DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE horse (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    number INTEGER NOT NULL,
    odds TEXT NOT NULL,
    race_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (race_id) REFERENCES race (id)
);

CREATE TABLE bet (
    id SERIAL PRIMARY KEY,
    horse_id INTEGER NOT NULL,
    race_id INTEGER NOT NULL,
    horseracing_user_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    each_way INTEGER NOT NULL,
    amount_won REAL DEFAULT 0,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (horse_id) REFERENCES horse (id),
    FOREIGN KEY (race_id) REFERENCES race (id),
    FOREIGN KEY (horseracing_user_id) REFERENCES horseracing_user (id)
);

CREATE TABLE result (
    id SERIAL PRIMARY KEY,
    horse_id INTEGER NOT NULL,
    race_id INTEGER NOT NULL,
    place INTEGER NOT NULL DEFAULT 10000,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (race_id) REFERENCES race (id),
    FOREIGN KEY (horse_id) REFERENCES horse (id)
);