DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS horse;
DROP TABLE IF EXISTS race;
DROP TABLE IF EXISTS bet;
DROP TABLE IF EXISTS result;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  amount REAL NOT NULL DEFAULT 10.0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE horse (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    number INTEGER NOT NULL,
    odds TEXT NOT NULL,
    race_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (race_id) REFERENCES race (id)
);

CREATE TABLE result (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    horse_id INTEGER NOT_NULL,
    race_id INTEGER NOT NULL,
    place INTEGER NOT NULL DEFAULT 10000,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (race_id) REFERENCES race (id),
    FOREIGN KEY (horse_id) REFERENCES horse (id)
);

CREATE TABLE race (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  number INTEGER UNIQUE NOT NULL,
  venue TEXT NOT NULL,
  distance TEXT NOT NULL,
  type TEXT NOT NULL,
  field TEXT NOT NULL,
  open INTEGER NOT NULL DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bet (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    horse_id INTEGER NOT NULL,
    race_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    each_way INTEGER NOT NULL,
    amount_won REAL DEFAULT 0,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (horse_id) REFERENCES horse (id),
    FOREIGN KEY (race_id) REFERENCES race (id),
    FOREIGN KEY (user_id) REFERENCES user (id)
);